### ISSUE TITLE
Svelte template

### ISSUE THREAD

**Issue by pappasa** [ServiceStack/docs.servicestack.net#1]
When I run the svelte template I get the below message:

npm run dev

> my-app@1.0.0 dev
> rollup -c -w

rollup v2.60.1
bundles src/main.ts → wwwroot\bundle.js...
LiveReload enabled
(!) Use of eval is strongly discouraged
https://rollupjs.org/guide/en/#avoiding-eval
node_modules\@servicestack\client\dist\index.js
21:             typeof process.versions.node !== 'undefined';
22:         if (isNode)
23:             return eval('require');
                       ^
rollup v2.60.1
bundles src/main.ts → wwwroot\bundle.js...
LiveReload enabled
(!) Use of eval is strongly discouraged
https://rollupjs.org/guide/en/#avoiding-eval
node_modules\@servicestack\client\dist\index.js
21:             typeof process.versions.node !== 'undefined';
22:         if (isNode)
23:             return eval('require');
                       ^
24:         return null;
25:     }
created wwwroot\bundle.js in 2.9s

How can I fix it?

**Comment by mythz** [comment]
This looks like it's just a warning, but it can be resolved by upgrading deps as done in [this commit](https://github.com/NetCoreTemplates/svelte-spa/commit/de9c0af0ff2adb9b518efb8ae906315053920c3b) which is available in the latest `svelte-spa` template.

Note: Registered Licensed developers can submit issues to: https://github.com/ServiceStack/Issues
